### ISSUE TITLE
Stage 2 items

### ISSUE THREAD

**Issue by brianteeman** [joomla/user-interface-text#24]
- [x]  Captcha case added to the style guide
- [x]  ip ==>IP added to the style guide
- [x]  review the use of access level instead of something more appropriate like view level https://github.com/joomla/user-interface-text/issues/11
- [x]  Custom HTML module rename https://github.com/joomla/user-interface-text/issues/18
- [x]   `"_QQ_"` to `"` for URLs and classes in the string values and resolve issue with debug https://github.com/joomla/user-interface-text/issues/28
- [x]  Replace all occurrences of admin and administrator with Backend #26 
- [x]  Show, Hide, Display #20 
- [ ]  enable or unblock a user https://github.com/joomla/joomla-cms/issues/5637
- [x] Joomla name usage #43 
- [x] Using/removing Manager #42 
- [x] Tooltip #38 
- [x] Submit / Send on forms #35 
- [x] Select / Click / Choose #31
